#!/bin/sh
setxkbmap -option caps:escape
setxkbmap -option altwin:swap_lalt_lwin

export GTK_THEME=Adwaita:dark
export GTK_APPLICATION_PREFER_DARK_THEME=1
export QT_QPA_PLATFORMTHEME=qt5ct

pkillall -qw picom
picom --config ~/.config/picom/picom.conf &

bspc config border_width 2
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#000000"
bspc config top_padding 34

feh --bg-scale ~/Documents/Code/background/images/swisstrain_c.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9

polybar-msg cmd quit
polybar mybar &

sxhkd &
